version: '3'
services:
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - "10000:10000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb+srv://srushtivirendradeshmukh_db_user:6IeW9SxBjBkc2pPZ@cluster0.mltney5.mongodb.net/
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
